# file: roles/postgres/tasks/main.yml
---


  - name: add postgres9.3 ppa
    sudo: yes
    apt_repository: repo="{{ item }}" state="present"
    with_items:
        - deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main
        
        
# add postgres 9.3 repo
# cat /etc/apt/sources.list.d/pgdg.list
# deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main
# wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
# sudo apt-get update
# sudo apt-get install postgresql-9.3 pgadmin3
    
  - name: add postgres9.3 key
    sudo: yes
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present  

  - name: package install
    sudo: yes
    apt: pkg="{{ item }}" state="present" update_cache="yes"
    with_items:
      - postgresql-9.3
      - pgadmin3
  
  # create user & database, grant privileges
  - name: create user
    sudo: yes
    sudo_user: postgres
    postgresql_user: name={{ project }} password={{ project }} state=present
  
  - name: create database
    sudo: yes
    sudo_user: postgres
    postgresql_db: name={{ project }} state=present
    
  - name: grant privileges
    sudo: yes
    sudo_user: postgres
    postgresql_privs: >
        type=database
        database={{ project }}
        role={{ project }}
        privs=ALL
    
  - name: install pg_dump
    sudo: yes
    pip: name="psycopg2"
    
  - name: create backup script
    sudo: yes
    template: >
      src=../templates/pgbackup.sh.j2
      dest=/var/lib/postgresql/pgbackup.sh
      mode=500
      owner=postgres
      group=www-data
    
  - name: create backup directory
    sudo: yes
    file: "{{ item }}"
    with_items:
      - "path=/mnt/s3/{{ project }} owner='{{ root_user }}' mode=770 group='www-data' state=directory"
    
  - name: create regular backup
    sudo: yes
    cron: >
      name="backup for sql db {{ project }}"
      user="postgres"
      hour="1"
      minute="59"
      job="/var/lib/postgresql/pgbackup.sh > /tmp/pgbackup.output 2>&1"
#            job="pg_dump {{ project }} > /mnt/s3/{{ project }}/`date +%s`.{{ project }}.sql"