# file: roles/postgres/tasks/main.yml
---

  - name: add postgres9.3 ppa
    sudo: yes
    apt_repository: repo="{{ item }}" state="present"
    with_items:
        - deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main
    
  - name: add postgres9.3 key
    sudo: yes
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present  

  - name: package install
    sudo: yes
    apt: pkg="{{ item }}" state="present" update_cache="yes"
    with_items:
      - postgresql-9.3
      - python-pip
      - pgadmin3
      - libpq-dev
      - python-dev

  - name: install pg_dump
    sudo: yes
    pip: name="psycopg2"
    
  # create user & database, grant privileges
  - name: create user
    sudo: yes
    sudo_user: postgres
    postgresql_user: name={{ item.user }} password={{ item.user }} state=present
    with_items: databases
  
  - name: create database
    sudo: yes
    sudo_user: postgres
    postgresql_db: name={{ item.database }} state=present
    with_items: databases
    
  - name: grant privileges
    sudo: yes
    sudo_user: postgres
    postgresql_privs: >
        type=database
        database={{ item.database  }}
        role={{ item.user }}
        privs=ALL
    with_items: databases
